version: 1.0.{build}
image:
  - Visual Studio 2015
environment:
  TEST_TARGET: ContinuousIntegration
  matrix:
    - CAKE_SCRIPT_NAME: vs2015

for:
-
  matrix:
    exclude:
      - image: Visual Studio 2015
        CAKE_SCRIPT_NAME: vs2017
-
  matrix:
    only:
      - image: Ubuntu
  install:
    - sudo apt-get update || echo "Update failed, ignoring..."
    - sudo apt-get install -y libgit2-dev

build_script:
  - ps: |
      ./build.ps1
      exit $LASTEXITCODE
