version: 1.0.{build}
image:
  #- macOS
  #- Ubuntu
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019
environment:
  matrix:
    - CAKE_SCRIPT_NAME: NetCore
    - CAKE_SCRIPT_NAME: vs2015
    - CAKE_SCRIPT_NAME: vs2017

for:
-
  matrix:
    only:
      - CAKE_SCRIPT_NAME: vs2015
  image: Visual Studio 2015
-
  matrix:
    only:
      - CAKE_SCRIPT_NAME: vs2017
  image: Visual Studio 2017
-
  matrix:
    only:
      - image: Ubuntu
  install:
    - sudo apt-get update || echo "Update failed, ignoring..."
    - sudo apt-get install -y libgit2-dev

build_script:
  - pwsh: |
      Invoke-WebRequest -Uri "https://raw.githubusercontent.com/cake-contrib/Cake.Recipe/develop/tools/packages.config" -OutFile .\tools\packages.config -UseBasicParsing
      ./build.ps1 -target CI -Verbosity Diagnostic
      if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
      }

artifacts:
  - path: '**/*.opencover.xml'