version: 1.0.{build}
branches:
    except:
    - master # We don't want to accidently publish a release to NuGet
image:
  #- macOS
  #- Ubuntu
  - Visual Studio 2019
  - Visual Studio 2017
  - Visual Studio 2015
environment:
  CAKE_PKG_CONFIG: https://raw.githubusercontent.com/cake-build/resources/develop/packages.config
  CAKE_TOOL_CONFIG: https://raw.githubusercontent.com/cake-contrib/Cake.Recipe/develop/.config/dotnet-tools.json
  matrix:
    - CAKE_SCRIPT_NAME: NetCore
    - CAKE_SCRIPT_NAME: vs2015
    - CAKE_SCRIPT_NAME: vs2017

for:
-
  matrix:
    exclude:
      - image: Visual Studio 2015
        CAKE_SCRIPT_NAME: vs2017
      - image: Visual Studio 2015
        CAKE_SCRIPT_NAME: NetCore
      - image: Visual Studio 2017
        CAKE_SCRIPT_NAME: NetCore
      - image: Visual Studio 2019
        CAKE_SCRIPT_NAME: vs2015 # Not compatible with VS 2019 it seems
-
  matrix:
    only:
      - image: Visual Studio 2019
- matrix:
    only:
      - image: Visual Studio 2019
        CAKE_SCRIPT_NAME: NetCore
  environment:
    FEEDZ_API_KEY:
      secure: txn+oD4p2fPGINTr3SOKUj25dinDSoHeVCrt0TGGJi0luHkeUdTwGtXZbsqP7x32
-
  matrix:
    only:
      - image: Ubuntu
  install:
    - sudo apt-get update || echo "Update failed, ignoring..."
    - sudo apt-get install -y libgit2-dev

build_script:
  - dotnet --info
  - pwsh: |
      if (!(Test-Path .config)) {
          mkdir .config
      }
  - pwsh: |
      Invoke-WebRequest -Uri "$env:CAKE_TOOL_CONFIG" -OutFile .\.config\dotnet-tools.json -UseBasicParsing
      Invoke-WebRequest -Uri "$env:CAKE_PKG_CONFIG" -OutFile .\tools\packages.config -UseBasicParsing
      if ($env:APPVEYOR_BUILD_WORKER_IMAGE-eq "Visual Studio 2019") {
        ./build.ps1 -target CI -Verbosity Diagnostic -UseNetCore
      }
      else {
        ./build.ps1 -target CI -Verbosity Diagnostic
      }
      if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
      }
test: off
