language: csharp

dist: xenial
os:
  - linux
  - osx

mono:
  - 6.6.0
  - latest

dotnet: 3.1.301

env:
  - CAKE_SCRIPT_NAME=vs2015
    PACKAGE_VERSION="2.0.0-alpha0272"
  - CAKE_SCRIPT_NAME=vs2017
    PACKAGE_VERSION="2.0.0-alpha0272"
  - CAKE_SCRIPT_NAME=NetCore
    PACKAGE_VERSION="2.0.0-alpha0272"

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq dotnet-sdk-2.1 ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew tap isen-ng/dotnet-sdk-versions ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cask install dotnet-sdk-2.1.800 ; fi

script:
  - ./build.sh --verbosity=diagnostic --target=CI
