language: csharp

dist: xenial
git:
  depth: false

jobs:
  include:
    - os: linux
      mono: 6.6.0
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=NetCore
          pkgConfigUrl=https://raw.githubusercontent.com/cake-contrib/Cake.Recipe/develop/tools/packages.config
    - os: linux
      mono: latest
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=NetCore
          pkgConfigUrl=https://raw.githubusercontent.com/cake-build/resources/develop/packages.config
    - os: osx
      mono: 6.6.0
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=NetCore
          pkgConfigUrl=https://raw.githubusercontent.com/cake-contrib/Cake.Recipe/develop/tools/packages.config
    - os: osx
      mono: latest
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=NetCore
          pkgConfigUrl=https://raw.githubusercontent.com/cake-build/resources/develop/packages.config
    - os: linux
      mono: 6.6.0
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=vs2015
          pkgConfigUrl=https://raw.githubusercontent.com/cake-contrib/Cake.Recipe/develop/tools/packages.config
    - os: linux
      mono: latest
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=vs2015
          pkgConfigUrl=https://raw.githubusercontent.com/cake-build/resources/develop/packages.config
    - os: osx
      mono: 6.6.0
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=vs2015
          pkgConfigUrl=https://raw.githubusercontent.com/cake-contrib/Cake.Recipe/develop/tools/packages.config
    - os: osx
      mono: latest
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=vs2015
          pkgConfigUrl=https://raw.githubusercontent.com/cake-build/resources/develop/packages.config
    - os: linux
      mono: 6.6.0
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=vs2017
          pkgConfigUrl=https://raw.githubusercontent.com/cake-contrib/Cake.Recipe/develop/tools/packages.config
    - os: linux
      mono: latest
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=vs2017
          pkgConfigUrl=https://raw.githubusercontent.com/cake-build/resources/develop/packages.config
    - os: osx
      mono: 6.6.0
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=vs2017
          pkgConfigUrl=https://raw.githubusercontent.com/cake-contrib/Cake.Recipe/develop/tools/packages.config
    - os: osx
      mono: latest
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=vs2017
          pkgConfigUrl=https://raw.githubusercontent.com/cake-build/resources/develop/packages.config

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq dotnet-sdk-2.1 ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew tap isen-ng/dotnet-sdk-versions ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cask install dotnet-sdk-2.1.800 ; fi
  - curl -L $pkgConfigUrl -o tools/packages.config

script:
  - if [ "$CAKE_SCRIPT_NAME" = "NetCore" ]; then ./build_netcore.sh --verbosity=Diagnostic --target=CI; else ./build.sh --verbosity=diagnostic --target=CI; fi
