language: csharp

dist: xenial
git:
  depth: false

jobs:
  include:
    - os: linux
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=NetCore
          toolConfigUrl=https://raw.githubusercontent.com/cake-contrib/Cake.Recipe/develop/.config/dotnet-tools.json
    - os: linux
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=NetCore
    - os: osx
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=NetCore
          toolConfigUrl=https://raw.githubusercontent.com/cake-contrib/Cake.Recipe/develop/.config/dotnet-tools.json
    - os: osx
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=NetCore
    - os: linux
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=vs2015
          toolConfigUrl=https://raw.githubusercontent.com/cake-contrib/Cake.Recipe/develop/.config/dotnet-tools.json
    - os: linux
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=vs2015
          pkgConfigUrl=https://raw.githubusercontent.com/cake-build/resources/develop/packages.config
    - os: osx
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=vs2015
          toolConfigUrl=https://raw.githubusercontent.com/cake-contrib/Cake.Recipe/develop/.config/dotnet-tools.json
    - os: osx
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=vs2015
          pkgConfigUrl=https://raw.githubusercontent.com/cake-build/resources/develop/packages.config
    - os: linux
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=vs2017
          toolConfigUrl=https://raw.githubusercontent.com/cake-contrib/Cake.Recipe/develop/.config/dotnet-tools.json
    - os: linux
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=vs2017
          pkgConfigUrl=https://raw.githubusercontent.com/cake-build/resources/develop/packages.config
    - os: osx
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=vs2017
          toolConfigUrl=https://raw.githubusercontent.com/cake-contrib/Cake.Recipe/develop/.config/dotnet-tools.json
    - os: osx
      dotnet: 3.1.301
      env:
        - CAKE_SCRIPT_NAME=vs2017
          pkgConfigUrl=https://raw.githubusercontent.com/cake-build/resources/develop/packages.config

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq dotnet-sdk-2.1 ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew tap isen-ng/dotnet-sdk-versions ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cask install dotnet-sdk-2.1.800 ; fi
  - if [ ! -z "$pkgConfigUrl" ]; then curl -L $pkgConfigUrl -o tools/packages.config ; fi
  - if [ ! -z "$toolConfigUrl" ]; then if [ ! -d ".config" ]; then mkdir .config ; fi ; curl -L $toolConfigUrl -o .config/dotnet-tools.json ; fi

script:
  - if [ ! -z "$toolConfigUrl" ]; then ./build.sh --verbosity=Diagnostic --target=CI --usenetcore ; fi
  - if [ -z "$toolConfigUrl" ]; then ./build.sh --verbosity=Diagnostic --target=CI ; fi
